import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased grid p-3 grid-cols-[100px_1fr] gap-4 bg-[#09090B] h-screen"
      >
        <aside className="bg-[#0e0e10] rounded-lg">aside</aside>
        <main className="bg-[#0e0e10] rounded-lg">{children}</main>
      </body>
    </html>
  );
}
