import type { Metadata } from 'next'
import React from 'react'

import Aside from '@/components/Aside'
import Main from '@/components/Main'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="grid h-screen grid-cols-[70px_1fr] gap-4 bg-[#09090B] p-2 antialiased">
        <Aside />
        <Main>{children}</Main>
      </body>
    </html>
  )
}
