import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased grid grid-cols-[200px_1fr]`}
      >
        <aside>aside</aside>
        <main>{children}</main>
      </body>
    </html>
  );
}
